apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-logistique-dhomeco-fr-tls
  namespace: logistics
spec:
  secretName: api-logistique-dhomeco-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: api.logistique.dhomeco.fr
  dnsNames:
  - api.logistique.dhomeco.fr