apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: logistics
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: tktorza/backup-cronjob:1
            imagePullPolicy: Always
            command: ["/bin/sh", "/script.sh"]
            env:
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: backup-cronjob
                    key: POSTGRES_DB
              - name: POSTGRES_HOST
                valueFrom:
                  configMapKeyRef:
                    name: backup-cronjob
                    key: POSTGRES_HOST
              - name: POSTGRES_PORT
                valueFrom:
                  configMapKeyRef:
                    name: backup-cronjob
                    key: POSTGRES_PORT
              - name: BACKUP_PATH
                valueFrom:
                  configMapKeyRef:
                    name: backup-cronjob
                    key: BACKUP_PATH
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: backup-cronjob
                    key: POSTGRES_USER
              - name: HOST_IP
                valueFrom:
                  configMapKeyRef:
                    name: backup-cronjob
                    key: HOST_IP
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: backup-cronjob
                    key: POSTGRES_PASSWORD
              - name: HOST_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: backup-cronjob
                    key: HOST_PASSWORD
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: docker-hub-secret