apiVersion: v1
kind: ConfigMap
metadata:
  name: logistics-configmap
  namespace: logistics
data:
  FUNCTIONAL_API_IMAGE_FOLDER_PATH: uploads
  SERVER_PORT: "5001"
  POSTGRES_HOST: postgres-0.postgres.default.svc.cluster.local
  POSTGRES_DB: logistique
  POSTGRES_PORT: "5432"