kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: storage-media