apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: compta
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: tktorza/compta-nodejs:4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: compta
                key: SERVER_PORT
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: compta
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: compta
                key: POSTGRES_DB
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: compta
                key: POSTGRES_PORT
          - name: FRONTEND_URL
            valueFrom:
              configMapKeyRef:
                name: compta
                key: FRONTEND_URL
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: compta-secret
                key: DATABASE_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: compta-secret
                key: JWT_SECRET
          - name: PASSPHRASE_REFRESH
            valueFrom:
              secretKeyRef:
                name: compta-secret
                key: PASSPHRASE_REFRESH
          - name: PASSPHRASE_KEY
            valueFrom:
              secretKeyRef:
                name: compta-secret
                key: PASSPHRASE_KEY
      imagePullSecrets:
      - name: docker-hub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: compta
spec:
  selector:
    app: nodejs
  ports:
  - port: 5001
    targetPort: 3000