apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-deviance-harlock-fr-tls
  namespace: deviance
spec:
  secretName: chat-deviance-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: chat.deviance.harlock.fr
  dnsNames:
  - chat.deviance.harlock.fr