apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-seve-harlock-fr-tls
  namespace: seve
spec:
  secretName: api-seve-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: api.seve.harlock.fr
  dnsNames:
  - api.seve.harlock.fr