apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: seve
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: harlock.allaire@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx