kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pictures
  namespace: seve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: pictures-seve