apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-auth
  namespace: deviance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-auth
  template:
    metadata:
      labels:
        app: redis-auth
    spec:
      containers:
        - name: redis-auth
          image: redis:7
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-auth
  namespace: deviance
spec:
  selector:
    app: redis-auth
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
