apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beta-api-gestion-dhomeco-fr-tls
  namespace: gestionbeta
spec:
  secretName: beta-api-gestion-dhomeco-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: beta.api.gestion.dhomeco.fr
  dnsNames:
  - beta.api.gestion.dhomeco.fr