apiVersion: v1
kind: ConfigMap
metadata:
  name: gestionbeta-configmap
  namespace: gestionbeta
data:
  FUNCTIONAL_API_IMAGE_FOLDER_PATH: uploads
  SERVER_PORT: "5001"
  POSTGRES_HOST: postgres-0.postgres.default.svc.cluster.local
  POSTGRES_DB: gestionbeta
  POSTGRES_PORT: "5432"