apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-api-trans-harlock-fr-tls
  namespace: trans
spec:
  secretName: chat-api-trans-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: chat.api.trans.harlock.fr
  dnsNames:
  - chat.api.trans.harlock.fr