apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: game-api-trans-harlock-fr-tls
  namespace: trans
spec:
  secretName: game-api-trans-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: game.api.trans.harlock.fr
  dnsNames:
  - game.api.trans.harlock.fr