kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: social
  namespace: trans
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: social-trans