apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trans-harlock-fr-tls
  namespace: trans
spec:
  secretName: trans-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: trans.harlock.fr
  dnsNames:
  - trans.harlock.fr