apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: shared-postgres
  hostPath:
    path: "/mnt/data"