apiVersion: v1
kind: PersistentVolume
metadata:
  name: social-trans
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: social-trans
  hostPath:
    path: "/mnt/data"