apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-ping
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: storage-excel
  hostPath:
    path: "/mnt/data"