apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-media
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: storage-media
  hostPath:
    path: "/mnt/data"