apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-gestion-dhomeco-fr-tls
  namespace: gestion
spec:
  secretName: api-gestion-dhomeco-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: api.gestion.dhomeco.fr
  dnsNames:
  - api.gestion.dhomeco.fr