apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: gestion
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tom@klack.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx