apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-ping-harlock-fr-tls
  namespace: ping
spec:
  secretName: api-ping-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: api.ping.harlock.fr
  dnsNames:
  - api.ping.harlock.fr