apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ping-harlock-fr-tls
  namespace: ping
spec:
  secretName: ping-harlock-fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: ping.harlock.fr
  dnsNames:
  - ping.harlock.fr