kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage
  namespace: ping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: storage-excel